from utils.config import Config, EvalConfig, TrainConfig

################################################## 
# Application
##############################################

# Book Info Application
cfg = Config(
                name='trainticket',
                services=[
                            'ts-admin-basic-info-service',
                            'ts-admin-order-service',
                            'ts-admin-route-service',
                            'ts-admin-travel-service',
                            'ts-admin-user-service',
                            'ts-assurance-mongo',
                            'ts-assurance-service',
                            'ts-auth-mongo',
                            #'ts-auth-service',
                            'ts-avatar-service',
                            'ts-basic-service',
                            'ts-cancel-service',
                            'ts-config-mongo',
                            'ts-config-service',
                            'ts-consign-mongo',
                            'ts-consign-price-mongo',
                            'ts-consign-price-service',
                            'ts-consign-service',
                            'ts-contacts-mongo',
                            'ts-contacts-service',
                            'ts-execute-service',
                            'ts-food-map-mongo',
                            'ts-food-map-service',
                            'ts-food-mongo',
                            'ts-food-service',
                            'ts-inside-payment-mongo',
                            'ts-inside-payment-service',
                            'ts-news-service',
                            'ts-notification-service',
                            'ts-order-mongo',
                            'ts-order-other-mongo',
                            'ts-order-other-service',
                            'ts-order-service',
                            'ts-payment-mongo',
                            'ts-payment-service',
                            'ts-preserve-other-service',
                            'ts-preserve-service',
                            'ts-price-mongo',
                            'ts-price-service',
                            'ts-rebook-service',
                            'ts-route-mongo',
                            'ts-route-plan-service',
                            'ts-route-service',
                            'ts-seat-service',
                            'ts-security-mongo',
                            'ts-security-service',
                            'ts-station-mongo',
                            'ts-station-service',
                            'ts-ticket-office-mongo',
                            'ts-ticket-office-service',
                            'ts-ticketinfo-service',
                            'ts-train-mongo',
                            'ts-train-service',
                            'ts-travel-mongo',
                            'ts-travel-plan-service',
                            'ts-travel-service',
                            'ts-travel2-mongo',
                            'ts-travel2-service',
                            'ts-ui-dashboard',
                            'ts-user-mongo',
                            'ts-user-service',
                            'ts-verification-code-service',
                            'ts-voucher-mysql',
                            'ts-voucher-service',
                        ],
                deployments={
                            'ts-admin-basic-info-service': 10,
                            'ts-admin-order-service': 10,
                            'ts-admin-route-service': 10,
                            'ts-admin-travel-service': 10,
                            'ts-admin-user-service': 10,
                            'ts-assurance-mongo': 10,
                            'ts-assurance-service': 10,
                            'ts-auth-mongo': 10,
                            #'ts-auth-service': 10,
                            'ts-avatar-service': 10,
                            'ts-basic-service': 30,
                            'ts-cancel-service': 10,
                            'ts-config-mongo': 10,
                            'ts-config-service': 10,
                            'ts-consign-mongo': 10,
                            'ts-consign-price-mongo': 10,
                            'ts-consign-price-service': 10,
                            'ts-consign-service': 10,
                            'ts-contacts-mongo': 10,
                            'ts-contacts-service': 10,
                            'ts-execute-service': 10,
                            'ts-food-map-mongo': 10,
                            'ts-food-map-service': 10,
                            'ts-food-mongo': 10,
                            'ts-food-service': 10,
                            'ts-inside-payment-mongo': 10,
                            'ts-inside-payment-service': 10,
                            'ts-news-service': 10,
                            'ts-notification-service': 10,
                            'ts-order-mongo': 10,
                            'ts-order-other-mongo': 10,
                            'ts-order-other-service': 10,
                            'ts-order-service': 10,
                            'ts-payment-mongo': 10,
                            'ts-payment-service': 10,
                            'ts-preserve-other-service': 10,
                            'ts-preserve-service': 10,
                            'ts-price-mongo': 10,
                            'ts-price-service': 10,
                            'ts-rebook-service': 10,
                            'ts-route-mongo': 10,
                            'ts-route-plan-service': 10,
                            'ts-route-service': 30,
                            'ts-seat-service': 10,
                            'ts-security-mongo': 10,
                            'ts-security-service': 10,
                            'ts-station-mongo': 10,
                            'ts-station-service': 10,
                            'ts-ticket-office-mongo': 10,
                            'ts-ticket-office-service': 10,
                            'ts-ticketinfo-service': 10,
                            'ts-train-mongo': 10,
                            'ts-train-service': 10,
                            'ts-travel-mongo': 10,
                            'ts-travel-plan-service': 10,
                            'ts-travel-service': 30,
                            'ts-travel2-mongo': 10,
                            'ts-travel2-service': 10,
                            'ts-ui-dashboard': 10,
                            'ts-user-mongo': 10,
                            'ts-user-service': 10,
                            'ts-verification-code-service': 10,
                            'ts-voucher-mysql': 10,
                            'ts-voucher-service': 10,
                            },
                cpu_requests=600,
                mem_requests=2000,
                #host='http://34.122.163.218:32677',
                host='http://35.232.246.231:80',
                autoscale_path='microservices/tt/mem_autoscale'
            )


##############################################
#### Training
##############################################

# 1. 50ms Median Latency
train_cfg = TrainConfig(
                            train_rps=[250,500,750,1000], 
                            train_iters=10, 
                            latency_threshold=50, 
                            c=2, 
                            w_l=1, 
                            w_i=3, 
                            min_iters=5, 
                            locustfile='load_generator/locustfiles/trainticket/default.py',
                            pod_filter='ts-station-service',
                            req_names=[],
                            search_strategy='cpu',
                            sample_duration=60,
                            cluster_name='cola2',
                            project_name='vig-cloud',
                            zone='us-central1-c',
                            node_pool='ob-pool',
                            max_nodes=200,
                            lat_opt='Average Latency'
                        )



train_cfg_tail = TrainConfig(
                            train_rps=[250,500,750,1000],
                            train_iters=15,
                            latency_threshold=100,
                            c=2,
                            w_l=1,
                            w_i=3,
                            min_iters=5,
                            locustfile='load_generator/locustfiles/trainticket/default.py',
                            pod_filter='ts-station-service',
                            req_names=[],
                            search_strategy='cpu',
                            sample_duration=80,
                            cluster_name='cola2',
                            project_name='vig-cloud',
                            zone='us-central1-c',
                            node_pool='ob-pool',
                            max_nodes=250,
                            lat_opt='90p Latency'
                        )


# TT Application
eval_cfg_ramp = EvalConfig(
                            name='ramp_insample',
                            services=cfg.services,
                            deployments=cfg.deployments,
                            cpu_requests=600,
                            mem_requests=2000,

                            host=cfg.host,
                            locustfile='load_generator/locustfiles/trainticket/default.py',
                            cluster_name='cola2',
                            project_name='vig-cloud',
                            zone='us-central1-c',
                            node_pool='ob-pool',
                            min_nodes=1,
                            max_nodes=700,

                            application='trainticket',
                            rps_rates=[250,500,750,500,250],
                            cpu_policies=[30,70],
                            bandit_policy='100_ms_tail',
                            train_config_path='/home/packard2700/autoscale-bandit/models/trainticket/bandit-100-tail-2',
                            pod_filter='ts-station-service',
                            duration=600,
                            num_iters=1,
                            wait_time=0,
                            reset_cluster=False,
                            autoscale_path=cfg.autoscale_path,
                        )


eval_cfg_ramp_oos = EvalConfig(
                            name='ramp_oosample',
                            services=cfg.services,
                            deployments=cfg.deployments,
                            cpu_requests=600,
                            mem_requests=2000,

                            host=cfg.host,
                            locustfile='load_generator/locustfiles/trainticket/default.py',
                            cluster_name='cola2',
                            project_name='vig-cloud',
                            zone='us-central1-c',
                            node_pool='ob-pool',
                            min_nodes=1,
                            max_nodes=700,

                            application='trainticket',
                            rps_rates=[300,450,650,450,300],
                            cpu_policies=[30,70],
                            bandit_policy='100_ms_tail',
                            train_config_path='/home/packard2700/autoscale-bandit/models/trainticket/bandit-100-tail-2',
                            pod_filter='ts-station-service',
                            duration=600,
                            num_iters=1,
                            wait_time=0,
                            reset_cluster=False,
                            autoscale_path=cfg.autoscale_path,
                        )

